#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 finlay@tuta.com
# zig-cc pinned to macOS 11 or later on x86_64, so libsodium's autotools get the target without an env var.
ZIG_TARGET=x86_64-macos.11.0 exec "$(dirname "$0")/zig-cc" "$@"
